
tiziano_mac_mini:
  paths:
    src_path: "/Users/tizianocausin/Desktop/project1917-26/python_scripts/src"
    data_path: "/Users/tizianocausin/1917_local"
    useful_stuff_path: "/Users/tizianocausin/Desktop/useful_stuff/python_scripts/src"

o2_cluster:
  paths:
    src_path: "/home/tic569/project1917-26/python_scripts/src"
    data_path: "/n/data2/hms/neurobio/livingstone/tiziano/1917_o2"
    useful_stuff_path: "/home/tic569/useful_stuff/python_scripts/src"


subjects: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 28, 30, 31, 34]
